package ro.mateistanescu.matquizspringbootbackend.entity;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Represent a single quiz question generated by the Gemini AI API.
 */
@Entity
@Table(name = "questions")
@Data
public class Question {
    @Id
    @GeneratedValue( strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "game_room_id", nullable = false)
    private GameRoom gameRoom;

    @Column(name = "question_text", nullable = false, columnDefinition = "TEXT")
    private String questionText;

    /**
     * Stores the 4 answer options as a JSONB array in PostgreSQL.
     * <p>
     * The validation of the JSON format will be done by a separate ai_process service.
     * </p>
     * <p>
     * Example: ["Paris", "London", "Berlin", "Madrid"]
     * </p>
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb", nullable = false)
    private List<String> answers;

    @Column(name = "correct_index", nullable = false)
    private Integer correctIndex;

    @Column(name = "time_limit", nullable = false)
    private Integer timeLimit = 30; //seconds

    @Column(name = "order_index", nullable = false)
    private Integer orderIndex;

    /**
     * Set by the server when the question is broadcasted via WebSocket.
     * Used for server-side anti-cheat time validation.
     */
    @Column(name = "posted_at")
    private LocalDateTime postedAt;

    //TODO: Determine if this is necessary or a single query is enough in PlayerAnswerRepository
//    @OneToMany(mappedBy = "question", fetch = FetchType.LAZY)
//    @OrderBy("answeredAt ASC")
//    private List<PlayerAnswer> playerAnswers;

    @PrePersist
    protected void onCreate() {
        postedAt = LocalDateTime.now();
    }
}
