spring.application.name=matquiz-spring-boot-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/matquiz_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate