spring.application.name=matquiz-spring-boot-backend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5432/matquiz_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${SECURITY_SECRET}
jwt.accessTokenValidityMS=${SECURITY_VALIDITY}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

app.user.avatar.base-url=https://media.mateistanescu.ro/
app.user.avatar.image-count=13
