spring.application.name=matquiz-spring-boot-backend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/matquiz_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${SECURITY_SECRET}
jwt.accessTokenValidityMS=${SECURITY_VALIDITY}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

app.user.avatar.base-url=https://media.mateistanescu.ro/
app.user.avatar.image-count=13

app.resend.api-key=${RESEND_API_KEY:}
app.resend.from=${RESEND_FROM:MatQuiz <contact@matquiz.mateistanescu.ro>}
app.resend.to=${RESEND_TO:delivered@resend.dev}
